-- AlterTable
ALTER TABLE "Decision" ADD COLUMN     "globalAlpha" DOUBLE PRECISION NOT NULL DEFAULT 10.0,
ADD COLUMN     "globalBeta" DOUBLE PRECISION NOT NULL DEFAULT 1.0;

-- AlterTable
ALTER TABLE "choices" ADD COLUMN     "mu" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sigmaSq" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
